# Generated by Django 5.2 on 2025-05-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_branch_client_employee_remove_clothes_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
    ]
