# Generated by Django 5.2 on 2025-05-05 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_loanapplication_applied_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_firstname', models.CharField(max_length=255, verbose_name='Фамилия покупателя')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
                ('buyer_surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество покупателя')),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('SH', 'Вывоз из магазина'), ('Доставка  курьером', 'CR'), ('Пункт выдачи заказов', 'PP')], default='SH', max_length=255, verbose_name='Тип доставки')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterField(
            model_name='branch',
            name='photo',
            field=models.ImageField(upload_to='image/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количесвто карт')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка  на поизицию')),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.card', verbose_name='Карта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказы',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cards',
            field=models.ManyToManyField(through='shop.Pos_order', to='shop.card', verbose_name='Карты'),
        ),
    ]
