# Generated by Django 5.2 on 2025-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_alter_branch_photo_pos_order_order_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='client',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='card',
            name='photo',
            field=models.ImageField(default='Non', upload_to='cards/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('credit', 'Кредитная'), ('debit', 'Дебетовая'), ('kid', 'Детская'), ('gold', 'Золотая')], default='Кредитная', max_length=20, verbose_name='Тип карты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Вывоз из магазина', 'SH'), ('Доставка  курьером', 'CR'), ('PP', 'Пункт выдачи заказов')], default='SH', max_length=255, verbose_name='Тип доставки'),
        ),
    ]
