from django.urls import include, path
from .views import *

urlpatterns = [
    path('base', base_view, name='base'),
    path('about', about_view, name='about'),
    path('all_products', all_products_view, name='all_products'),
    path('cart', cart_view, name='cart'),
    path('categories', categories_view, name='categories'),
    path('contacts', contacts_view, name='contacts'),
    path('how_to_find', how_to_find_view, name='how_to_find'),
    path('index', index_view, name='index'),
    path('privacy', privacy_view, name='privacy'),
    path('product_detail', product_detail_view, name='product_detail'),
    path('clients/', ClientListView.as_view(), name='client-list'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client-detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client-create'),
    path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client-update'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client-delete'),
    path('accounts/', AccountListView.as_view(), name='account-list'),
    path('accounts/<int:pk>/', AccountDetailView.as_view(), name='account-detail'),
    path('accounts/create/', AccountCreateView.as_view(), name='account-create'),
    path('accounts/<int:pk>/update/', AccountUpdateView.as_view(), name='account-update'),
    path('accounts/<int:pk>/delete/', AccountDeleteView.as_view(), name='account-delete'),
    path('credits/', CreditListView.as_view(), name='credit-list'),
    path('credits/<int:pk>/', CreditDetailView.as_view(), name='credit-detail'),
    path('credits/create/', CreditCreateView.as_view(), name='credit-create'),
    path('credits/<int:pk>/update/', CreditUpdateView.as_view(), name='credit-update'),
    path('credits/<int:pk>/delete/', CreditDeleteView.as_view(), name='credit-delete'),
    path('transactions/', TransactionListView.as_view(), name='transaction-list'),
    path('transactions/<int:pk>/', TransactionDetailView.as_view(), name='transaction-detail'),
    path('transactions/create/', TransactionCreateView.as_view(), name='transaction-create'),
    path('transactions/<int:pk>/update/', TransactionUpdateView.as_view(), name='transaction-update'),
    path('transactions/<int:pk>/delete/', TransactionDeleteView.as_view(), name='transaction-delete'),
    path('loan-applications/', LoanApplicationListView.as_view(), name='loan-application-list'),
    path('loan-applications/<int:pk>/', LoanApplicationDetailView.as_view(), name='loan-application-detail'),
    path('loan-applications/create/', LoanApplicationCreateView.as_view(), name='loan-application-create'),
    path('loan-applications/<int:pk>/update/', LoanApplicationUpdateView.as_view(), name='loan-application-update'),
    path('loan-applications/<int:pk>/delete/', LoanApplicationDeleteView.as_view(), name='loan-application-delete'),
]
